"""empty message

Revision ID: ca555fdb9d76
Revises: 7d454d132da8
Create Date: 2024-07-29 16:18:55.396804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca555fdb9d76'
down_revision = '7d454d132da8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('follows_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['follows_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
